sudo: false
language: python
python:
- '2.7'
install:
- pip install flake8
- pip install pytest
- pip install pytest-cov
- pip install requests
- pip install scrutinizer-ocular
before_script:
- export PYTHONPATH="$PYTHONPATH:."
deploy:
  provider: pypi
  user: qiniusdk
  password:
    secure: MLmZbIXL4kFq0mOi9BprrHTaSNd0ATGTZ3Nw/OjoWlhNw0IaCcaVZgGcGUCE2698zME3YqTzKJ28jZOUKDneNyeBNlai9eS89abbU9onZRczb5xyiMdiqsMks1to+549xjmf/r95SaV/grK350Sy9H5RIMof5iNwCDMugyxnEeg=
  on:
    tags: true
